### ISSUE TITLE
whoisxmlapi.com

### ISSUE THREAD

**Issue by dadigi** [deralexxx/security-apis#11]
whoisxmlapi.com offers different APIs. Some can be used for free.
https://www.whoisxmlapi.com/products-overview.php

Whois API
Domain Availability API
Reverse Whois Api
Reverse IP Api
Reverse MX Api
Reverse NS Api
Brand Alert Api
Registrant Alert Api
Bulk Whois API
DNS Lookup API
Email Verification API
IP Geolocation API
Domain Reputation Scoring Api

**Comment by deralexxx** [comment]
Thx for the contribution, added it

https://github.com/deralexxx/security-apis/commit/754d675778c62703bcd37a2263cfec3f2e1ab108
