### ISSUE TITLE
Lastline API

### ISSUE THREAD

**Issue by RobSche** [deralexxx/security-apis#12]
Hi Alex,

here the details for the Lastline API:

API | Description | Auth | HTTPS | Link | Free / Commercial
Lastline | Lastline Enterprise  | ApiKey | Yes | https://user.lastline.com/papi-doc/api/html/index.html | Commercial

also a link which can be referenced:

https://www.lastline.com/labsblog/lastline-its-as-easy-as-a-p-i/

Cheers

Robert

**Comment by deralexxx** [comment]
Thx, added it!
https://github.com/deralexxx/security-apis/commit/5caa38afc8ed1387c0752524892e9d2f1008cc4a
